src/hesabdari/apps/accounting/api/accounts/urls.py
from django.urls import path

from hesabdari.apps.accounting.api.accounts.views import accouns_manager, UpdateBulkAccount, delete_account, \
    edit_account, create_accounts, AccountsView

urlpatterns = [
    path('items/accounts-list/', AccountsView.as_view(), name='get_accounts_list'),
    path('items/accounts-list/create', create_accounts, name='create_accounts'),
    path('accounts/edit/<int:pk>/', edit_account, name='edit_account'),
    path('accounts/delete/<int:pk>/', delete_account, name='delete_account'),
    path('transfer-accounts/', UpdateBulkAccount.as_view(), name='transfer-accounts'),
    path('accounts-manager/', accouns_manager, name='accounts_manager'),

]

src/hesabdari/apps/accounts/urls.py
from django.urls import path

from hesabdari.apps.accounts.views import LoginView, RegisterView, VerifyView, logout_view, ResetPasswordView, \
    ForgetPasswordView, ResetVerifyView

app_name = 'profile'

urlpatterns =[
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('verify/', VerifyView.as_view(), name='verify'),
    path('reset-password/', ResetPasswordView.as_view(), name='reset_password'),
    path('forget-password/', ForgetPasswordView.as_view(), name='forget_password'),
    path('reset_verify/', ResetVerifyView.as_view(), name='reset_verify_password'),
    path('logout/', logout_view, name='logout'),
]

src/hesabdari/apps/users/urls.py
from django.urls import path

from hesabdari.apps.users.views import LoginView, RegisterView, VerifyView, logout_view, ResetPasswordView, \
    ForgetPasswordView, ResetVerifyView

app_name = 'profile'

urlpatterns =[
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('verify/', VerifyView.as_view(), name='verify'),
    path('reset-password/', ResetPasswordView.as_view(), name='reset_password'),
    path('forget-password/', ForgetPasswordView.as_view(), name='forget_password'),
    path('reset_verify/', ResetVerifyView.as_view(), name='reset_verify_password'),
    path('logout/', logout_view, name='logout'),
]

src/hesabdari/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("select2/", include("django_select2.urls")),
    path('accounting/', include('hesabdari.apps.accounting.api.urls')),
    path('profile/', include('hesabdari.apps.users.urls')),
    path('', include('hesabdari.apps.home.urls')),
    path('api-auth/', include('rest_framework.urls')),
    ]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/hesabdari/apps/accounting/models/accounts.py
from django.db import models
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel
from hesabdari.apps.users.models import User



class AccountsClass(MPTTModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='users', blank=True)
    name = models.CharField(max_length=255)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')

    class Meta:
        db_table = 'accounts'

    class MPTTMeta:
        order_insertion_by = ['name']

    def __str__(self):
        # Get all ancestors (excluding self) in order from root to parent
        ancestors = self.get_ancestors()

        # Collect ucode values from ancestors and self
        name_list = [ancestor.name for ancestor in ancestors if ancestor.name]  # Filter out None values
        if self.name:
            name_list.append(self.name)
        name_list = " > ".join(name_list) if name_list else "خالی"

        return f"{name_list}"

src/hesabdari/apps/accounts/models.py
import random
import uuid
from datetime import timedelta

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone


# Create your models here.

class User(AbstractUser):
    phone_number = models.CharField(max_length=12, unique=True)
    profile_picture = models.ImageField(upload_to='profile_pics/', blank=True, null=True)
    password_reset_token = models.CharField(
        max_length=100,  # A UUID is 32 chars, plus hyphens for some formats
        unique=True,
        blank=True,
        null=True,
        help_text="توکن ریست پسورد."
    )
    password_reset_token_expires_at = models.DateTimeField(
        blank=True,
        null=True,
        help_text="Timestamp when the password reset token expires."
    )

    def generate_password_reset_token(self):
        """Generates a new unique token and sets an expiration time."""
        # Ensure old token is cleared before generating a new one to maintain uniqueness
        self.password_reset_token = str(uuid.uuid4())  # Generate a UUID for uniqueness
        # Set expiration, e.g., 1 hour from now
        self.password_reset_token_expires_at = timezone.now() + timezone.timedelta(hours=1)
        self.save()
        return self.password_reset_token

    def is_password_reset_token_valid(self, token):
        """Checks if the given token is valid and not expired."""
        if not self.password_reset_token:
            return False  # No token exists for this user

        if self.password_reset_token != token:
            return False  # Token mismatch

        if self.password_reset_token_expires_at and \
                self.password_reset_token_expires_at < timezone.now():
            self.clear_password_reset_token()  # Clear expired token
            return False  # Token has expired

        return True

    def clear_password_reset_token(self):
        """Clears the password reset token and its expiration time."""
        self.password_reset_token = None
        self.password_reset_token_expires_at = None
        self.save()


    class Meta:
        db_table = 'user'

class ActivationCode(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    code = models.CharField(max_length=6)
    created_at = models.DateTimeField(auto_now_add=True)
    attempts = models.PositiveIntegerField(default=0)

    def generate_code(self):
        self.code = str(random.randint(100000, 999999))
        self.created_at = timezone.now()
        self.attempts = 0
        self.save()

    def is_expired(self):
        return timezone.now() > self.created_at + timedelta(minutes=5)

    def increment_attempt(self):
        self.attempts += 1
        self.save()

    def __str__(self):
        return f"{self.user.username} - {self.code}"

src/hesabdari/apps/accounting/api/accounts/views.py
import json

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum
from django.http import JsonResponse, Http404
from django.shortcuts import get_object_or_404, render
from django.template.loader import render_to_string
from django.views import generic

from hesabdari.apps.accounting.forms import AccountsForm
from hesabdari.apps.accounting.models.accounts import AccountsClass
from hesabdari.apps.accounting.models.balancesheet import BalanceSheet


def accouns_manager(request):
    return render(request, 'account_base/accounts-manager.html', {})

class AccountsView(generic.View):
    def get(self, request):
        def serialize_node(node, net_total):
            return {
                'id': str(node.id),
                'text': node.name,
                'parent': str(node.parent.id) if node.parent else '#',
                'li_attr': {'data-net-total': net_total},
            }

        # همه‌ی حساب‌ها رو با parent واکشی کن
        accounts = AccountsClass.objects.filter(user=request.user).select_related('parent')
        balances = BalanceSheet.objects.filter(user=request.user)
        # همه‌ی تراکنش‌های کاربر رو یکجا بگیر
        if request.GET.get('start-date'):
            start_date = str(request.GET.get('start-date'))
            balances = balances.filter(user=request.user, document__date_created__gte=start_date)
        if request.GET.get('end-date'):
            end_date = str(request.GET.get('end-date'))
            balances = balances.filter(user=request.user, document__date_created__lte=end_date)

        # جمع تراکنش‌ها بر اساس account_id
        totals = balances.values('account_id', 'transaction_type').annotate(total=Sum('amount'))

        # دیکشنری برای دسترسی سریع
        totals_dict = {}
        for row in totals:
            acc_id = row['account_id']
            ttype = row['transaction_type']
            amount = row['total'] or 0
            if acc_id not in totals_dict:
                totals_dict[acc_id] = {'debt': 0, 'credit': 0}
            totals_dict[acc_id][ttype] += amount

        data = []
        for account in accounts:
            # گرفتن descendantها (از treebeard یا mptt فرض می‌کنیم)
            descendants = account.get_descendants(include_self=True)

            total_debtor = 0
            total_creditor = 0
            for desc in descendants:
                if desc.id in totals_dict:
                    total_debtor += totals_dict[desc.id]['debt']
                    total_creditor += totals_dict[desc.id]['credit']

            net_total = total_creditor - total_debtor
            data.append(serialize_node(account, net_total))

        form_html = render_to_string('account_base/accounts.html', {
            'uniqueid': request.GET.get('uid', 'default')
        })

        return JsonResponse({'form_html': form_html, 'data': data})

def create_accounts(request):
    parent_id = request.POST.get('parent')
    form = AccountsForm(request.POST)
    if form.is_valid():
        new_account = form.save(commit=False)
        new_account.user = request.user
        if parent_id:
            new_account.parent_id = parent_id
        else:
            new_account.parent = None
        new_account.save()
        return JsonResponse({
            'success': True,
            'id': new_account.id,
            'name': new_account.name,
            'parent_id': new_account.parent.id if new_account.parent else None
        })
    else:
        return JsonResponse({'success': False, 'errors': form.errors})

def edit_account(request, pk):
    account = get_object_or_404(AccountsClass, pk=pk, user=request.user)
    name = request.POST.get('name')
    if name:
        account.name = name
        account.save()
        return JsonResponse({'success': True})
    return JsonResponse({'success': False, 'error': 'نام خالی است'})

def delete_account(request, pk):
    if request.method == 'POST':
        try:
            account = AccountsClass.objects.get(pk=pk, user=request.user)
            if account.get_children():
                return JsonResponse({'success': False, 'error': 'این حساب زیرمجموعه دارد'})
            if BalanceSheet.objects.filter(user=request.user.id).filter(account=account).exists():
                return JsonResponse({'success': False, 'error': 'این حساب در سندی در حال استفاده است.'})
            else:
                account.delete()
                return JsonResponse({'success': True})
        except AccountsClass.DoesNotExist:
            return JsonResponse({'success': False, 'error': 'حساب پیدا نشد'})
    else:
        raise Http404()

class UpdateBulkAccount(LoginRequiredMixin, generic.View):
    def post(self, request):
        data = json.loads(request.body)
        selected_ids = data.get("balances", [])
        transfer_value = data.get("transfer_value")
        balances = BalanceSheet.objects.filter(user=request.user,id__in=selected_ids)
        for balance in balances:
            balance.account_id = int(transfer_value)
        BalanceSheet.objects.bulk_update(balances, ['account_id'])
        return JsonResponse({"status": "ok", "received": selected_ids})

src/hesabdari/apps/accounting/views/account.py
import json

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum
from django.http import JsonResponse, Http404
from django.shortcuts import get_object_or_404, render
from django.template.loader import render_to_string
from django.views import generic

from hesabdari.apps.accounting.forms import AccountsForm
from hesabdari.apps.accounting.models import AccountsClass, BalanceSheet


def accouns_manager(request):
    return render(request, 'account_base/accounts-manager.html', {})

class AccountsView(generic.View):
    def get(self, request):
        def serialize_node(node, net_total):
            return {
                'id': str(node.id),
                'text': node.name,
                'parent': str(node.parent.id) if node.parent else '#',
                'li_attr': {'data-net-total': net_total},
            }

        # همه‌ی حساب‌ها رو با parent واکشی کن
        accounts = AccountsClass.objects.filter(user=request.user).select_related('parent')
        balances = BalanceSheet.objects.filter(user=request.user)
        # همه‌ی تراکنش‌های کاربر رو یکجا بگیر
        if request.GET.get('start-date'):
            start_date = str(request.GET.get('start-date'))
            balances = balances.filter(user=request.user, document__date_created__gte=start_date)
        if request.GET.get('end-date'):
            end_date = str(request.GET.get('end-date'))
            balances = balances.filter(user=request.user, document__date_created__lte=end_date)

        # جمع تراکنش‌ها بر اساس account_id
        totals = balances.values('account_id', 'transaction_type').annotate(total=Sum('amount'))

        # دیکشنری برای دسترسی سریع
        totals_dict = {}
        for row in totals:
            acc_id = row['account_id']
            ttype = row['transaction_type']
            amount = row['total'] or 0
            if acc_id not in totals_dict:
                totals_dict[acc_id] = {'debt': 0, 'credit': 0}
            totals_dict[acc_id][ttype] += amount

        data = []
        for account in accounts:
            # گرفتن descendantها (از treebeard یا mptt فرض می‌کنیم)
            descendants = account.get_descendants(include_self=True)

            total_debtor = 0
            total_creditor = 0
            for desc in descendants:
                if desc.id in totals_dict:
                    total_debtor += totals_dict[desc.id]['debt']
                    total_creditor += totals_dict[desc.id]['credit']

            net_total = total_creditor - total_debtor
            data.append(serialize_node(account, net_total))

        form_html = render_to_string('account_base/accounts.html', {
            'uniqueid': request.GET.get('uid', 'default')
        })

        return JsonResponse({'form_html': form_html, 'data': data})

def create_accounts(request):
    parent_id = request.POST.get('parent')
    form = AccountsForm(request.POST)
    if form.is_valid():
        new_account = form.save(commit=False)
        new_account.user = request.user
        if parent_id:
            new_account.parent_id = parent_id
        else:
            new_account.parent = None
        new_account.save()
        return JsonResponse({
            'success': True,
            'id': new_account.id,
            'name': new_account.name,
            'parent_id': new_account.parent.id if new_account.parent else None
        })
    else:
        return JsonResponse({'success': False, 'errors': form.errors})

def edit_account(request, pk):
    account = get_object_or_404(AccountsClass, pk=pk, user=request.user)
    name = request.POST.get('name')
    if name:
        account.name = name
        account.save()
        return JsonResponse({'success': True})
    return JsonResponse({'success': False, 'error': 'نام خالی است'})

def delete_account(request, pk):
    if request.method == 'POST':
        try:
            account = AccountsClass.objects.get(pk=pk, user=request.user)
            if account.get_children():
                return JsonResponse({'success': False, 'error': 'این حساب زیرمجموعه دارد'})
            if BalanceSheet.objects.filter(user=request.user.id).filter(account=account).exists():
                return JsonResponse({'success': False, 'error': 'این حساب در سندی در حال استفاده است.'})
            else:
                account.delete()
                return JsonResponse({'success': True})
        except AccountsClass.DoesNotExist:
            return JsonResponse({'success': False, 'error': 'حساب پیدا نشد'})
    else:
        raise Http404()

class UpdateBulkAccount(LoginRequiredMixin, generic.View):
    def post(self, request):
        data = json.loads(request.body)
        selected_ids = data.get("balances", [])
        transfer_value = data.get("transfer_value")
        balances = BalanceSheet.objects.filter(user=request.user,id__in=selected_ids)
        for balance in balances:
            balance.account_id = int(transfer_value)
        BalanceSheet.objects.bulk_update(balances, ['account_id'])
        return JsonResponse({"status": "ok", "received": selected_ids})

src/hesabdari/apps/users/templates/accounts/forget_password.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<body data-pc-preset="preset-1" data-pc-sidebar-theme="light" data-pc-sidebar-caption="true" data-pc-direction="rtl" data-pc-theme="light">
  <!-- [ Pre-loader ] start -->
  <div class="loader-bg">
    <div class="loader-track">
      <div class="loader-fill"></div>
    </div>
  </div>
  <!-- [ Pre-loader ] End -->

  <div class="auth-main v1">
    <div class="auth-wrapper">
      <div class="auth-form">
        <div class="card my-5">
          <div class="card-body">
            <div class="text-center">
              <img src="{% static 'images/authentication/img-auth-fporgot-password.png' %}" alt="images" class="img-fluid mb-3">
              <h4 class="f-w-500 mb-1"> رمز عبور را فراموش کرده اید</h4>
              <p class="mb-3"> بازگشت به <a href="{% url 'profile:login' %}" class="link-primary ms-1">ورود</a></p>
            </div>
              <form method="post">
                  {% csrf_token %}
            <div class="mb-3">
              <label class="form-label">{{ form.phone_number.label }}</label>
              {{ form.phone_number }}
            </div>
            <div class="d-grid mt-3">
              <button type="submit" class="btn btn-primary">ارسال کد به شماره تلفن</button>
            </div>
              </form>
          </div>
        </div>
      </div>

    </div>
  </div>
{% endblock %}

src/hesabdari/apps/users/templates/accounts/login-v1.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

<body data-pc-preset="preset-1" data-pc-sidebar-theme="light" data-pc-sidebar-caption="true" data-pc-direction="rtl" data-pc-theme="light">
  <!-- [ Pre-loader ] start -->
  <div class="loader-bg">
    <div class="loader-track">
      <div class="loader-fill"></div>
    </div>
  </div>
  <!-- [ Pre-loader ] End -->

  <div class="auth-main v1">
    <div class="auth-wrapper">
      <div class="auth-form">
        <div class="card my-5">
          <div class="card-body">
                        {% if form.non_field_errors %}
            <div class="alert alert-danger">
              {% for error in form.non_field_errors %}
                <div>{{ error }}</div>
              {% endfor %}
            </div>
          {% endif %}
            <div class="text-center">
              <img src="{% static 'images/authentication/img-auth-login.png' %}" alt="images" class="img-fluid mb-3">
              <h4 class="f-w-500 mb-1">با ایمیل خود وارد شوید</h4>
              <p class="mb-3">حساب ندارید؟ <a href="../pages/register-v1.html" class="link-primary ms-1">ایجاد حساب</a></p>
            </div>
            <form method="post">
                {% csrf_token %}
            <div class="mb-3">
                {{ form.username }}
            </div>
            <div class="mb-3">
                {{ form.password }}
            </div>
            <div class="d-flex mt-1 justify-content-between align-items-center">
              <div class="form-check">
                {{ form.remember_me  }}
                <label class="form-check-label text-muted" for="customCheckc1">{{ form.remember_me.label }}</label>
              </div>

              <a href="../pages/forgot-password-v1.html"><h6 class="f-w-400 mb-0">گذرواژه را فراموش کرده‌اید؟</h6></a>
            </div>
            <div class="d-grid mt-4">
              <button type="submit" class="btn btn-primary">ورود به سیستم</button>
            </div>
            </form>

            <div class="saprator my-3">
              <span>یا</span>
            </div>
            <div class="text-center">
              <ul class="list-inline mx-auto mt-3 mb-0">
                <li class="list-inline-item">
                  <a href="https://www.facebook.com/" class="avtar avtar-s rounded-circle bg-facebook" target="_blank">
                    <i class="fab fa-facebook-f text-white"></i>
                  </a>
                </li>
                <li class="list-inline-item">
                  <a href="https://twitter.com/" class="avtar avtar-s rounded-circle bg-twitter" target="_blank">
                    <i class="fab fa-twitter text-white"></i>
                  </a>
                </li>
                <li class="list-inline-item">
                  <a href="https://myaccount.google.com/" class="avtar avtar-s rounded-circle bg-googleplus" target="_blank">
                    <i class="fab fa-google text-white"></i>
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
  <!-- [ Main Content ] end -->
{% endblock %}

src/hesabdari/apps/users/templates/accounts/register-v1.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
    <body data-pc-preset="preset-1" data-pc-sidebar-theme="light" data-pc-sidebar-caption="true" data-pc-direction="rtl" data-pc-theme="light">
  <!-- [ Pre-loader ] start -->
  <div class="loader-bg">
    <div class="loader-track">
      <div class="loader-fill"></div>
    </div>
  </div>
  <!-- [ Pre-loader ] End -->

  <div class="auth-main v1">
    <div class="auth-wrapper">
      <div class="auth-form">
        <div class="card my-5">
            {% if form.non_field_errors %}
            <div class="alert alert-danger">
              {% for error in form.non_field_errors %}
                <div>{{ error }}</div>
            {% endfor %}
            </div>
          {% endif %}
        {% for field in form %}
            {% if field.errors %}
            <div class="alert alert-danger">
                {{ field.errors }}
            </div>
            {% endif %}
        {% endfor %}
            <form method="post">
                {% csrf_token %}
          <div class="card-body">
            <div class="text-center">
              <img src="{% static 'images/authentication/img-auth-register.png' %}" alt="images" class="img-fluid mb-3">
              <h4 class="f-w-500 mb-1">با شماره خود ثبت نام کنید</h4>
              <p class="mb-3">از قبل یک حساب دارید؟ <a href="../pages/login-v1.html" class="link-primary">ورود به سیستم</a></p>
            </div>

            <div class="row">
              <div class="col-sm-6">
                <div class="mb-3">
                    {{ form.first_name }}
                </div>
              </div>
              <div class="col-sm-6">
                <div class="mb-3">
                  {{ form.last_name }}
                </div>
              </div>
            </div>
            <div class="mb-3">
              {{ form.email }}
            </div>
            <div class="mb-3">
              {{ form.phone_number }}
            </div>
            <div class="mb-3">
              {{ form.password }}
            </div>
            <div class="mb-3">
              {{ form.confirm_password }}
            </div>
            <div class="d-flex mt-1 justify-content-between">
              <div class="form-check">
                <input class="form-check-input input-primary" type="checkbox" id="customCheckc1" checked="">
                <label class="form-check-label text-muted" for="customCheckc1">من با همه شرایط و ضوابط موافقم</label>
              </div>
            </div>
            <div class="d-grid mt-4">
              <button type="submit" class="btn btn-primary">ایجاد حساب</button>
            </div>
          </div>
            </form>
        </div>
      </div>
{% endblock %}

src/hesabdari/apps/users/templates/accounts/reset-password.html
{% extends 'base.html' %}
{% load static %}


{% block body %}
<body data-pc-preset="preset-1" data-pc-sidebar-theme="light" data-pc-sidebar-caption="true" data-pc-direction="rtl" data-pc-theme="light">
  <!-- [ Pre-loader ] start -->
  <div class="loader-bg">
    <div class="loader-track">
      <div class="loader-fill"></div>
    </div>
  </div>
  <!-- [ Pre-loader ] End -->

  <div class="auth-main v1">
    <div class="auth-wrapper">
      <div class="auth-form">
        <div class="card my-5">
          <div class="card-body">
            <div class="text-center">
              <img src="../assets/images/authentication/img-auth-reset-password.png" alt="images" class="img-fluid mb-3">
              <h4 class="f-w-500 mb-1">فراموشی رمز عبور</h4>
              <p class="mb-3"> بازگشت به <a href="../pages/login-v1.html" class="link-primary ms-1">ورود</a></p>
            </div>

              <form method="post">
            <div class="mb-3">
                {% csrf_token %}
              <label class="form-label">{{ form.password.label }}</label>
              {{ form.password }}
            </div>
            <div class="mb-3">
              <label class="form-label">{{ form.confirm_password.label }}</label>
              {{ form.confirm_password }}
            </div>
            <div class="d-grid mt-4">
              <button type="submit" class="btn btn-primary">فراموشی رمز عبور</button>
            </div>
              </form>

          </div>
        </div>
      </div>

    </div>
  </div>

{% endblock %}

src/hesabdari/apps/users/templates/accounts/reset_verify.html
{% extends 'base.html' %}

{% block body %}
    <body data-pc-preset="preset-1" data-pc-sidebar-theme="light" data-pc-sidebar-caption="true" data-pc-direction="rtl" data-pc-theme="light">
  <!-- [ Pre-loader ] start -->
  <div class="loader-bg">
    <div class="loader-track">
      <div class="loader-fill"></div>
    </div>
  </div>
  <!-- [ Pre-loader ] End -->

  <div class="auth-main v1">
    <div class="auth-wrapper">
      <div class="auth-form">
        <div class="card my-5">
          <div class="card-body">
            <div class="text-center">
              <img src="../assets/images/authentication/img-auth-code-varify.png" alt="images" class="img-fluid mb-3">
              <h4 class="f-w-500 mb-1">لطفاً با OTP تأیید کنید</h4>
              <p class="mb-0">ما کد را برای شما در jone ارسال کردیم. ****@company.com</p>
              <p class="mb-3">ایمیل را دریافت نکردید؟ <a href="#" class="link-primary ms-1">ارسال مجدد کد</a></p>
            </div>
              <form method="post">
                  {% csrf_token %}
            <div class="row my-4 g-3 text-center">
              <div class="col">
                {{ form.code }}
              </div>
            </div>
            <div class="d-grid mt-4">
              <button type="submit" class="btn btn-primary">ادامه</button>
            </div>
              </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

src/hesabdari/apps/users/templates/accounts/verify.html
{% extends 'base.html' %}

{% block body %}
    <body data-pc-preset="preset-1" data-pc-sidebar-theme="light" data-pc-sidebar-caption="true" data-pc-direction="rtl" data-pc-theme="light">
  <!-- [ Pre-loader ] start -->
  <div class="loader-bg">
    <div class="loader-track">
      <div class="loader-fill"></div>
    </div>
  </div>
  <!-- [ Pre-loader ] End -->

  <div class="auth-main v1">
    <div class="auth-wrapper">
      <div class="auth-form">
        <div class="card my-5">
          <div class="card-body">
            <div class="text-center">
              <img src="../assets/images/authentication/img-auth-code-varify.png" alt="images" class="img-fluid mb-3">
              <h4 class="f-w-500 mb-1">لطفاً با OTP تأیید کنید</h4>
              <p class="mb-0">ما کد را برای شما در jone ارسال کردیم. ****@company.com</p>
              <p class="mb-3">ایمیل را دریافت نکردید؟ <a href="#" class="link-primary ms-1">ارسال مجدد کد</a></p>
            </div>
              <form method="post">
                  {% csrf_token %}
            <div class="row my-4 g-3 text-center">
              <div class="col">
                {{ form.code }}
              </div>
            </div>
            <div class="d-grid mt-4">
              <button type="submit" class="btn btn-primary">ادامه</button>
            </div>
              </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}